# Generated by Django 4.0.5 on 2022-06-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='language',
            field=models.CharField(blank=True, help_text='Language preferred by the vendor', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
