# Generated by Django 4.0.5 on 2022-06-13 03:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0004_alter_servicearea_geom_alter_servicearea_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
