# Generated by Django 4.0.5 on 2022-06-13 06:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0005_alter_servicearea_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoapi.provider')),
                ('service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoapi.servicearea')),
            ],
        ),
    ]
