# Generated by Django 4.0.5 on 2022-06-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0009_alter_geolocation_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='currency_currency',
        ),
    ]
