# Generated by Django 4.0.5 on 2022-06-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0010_remove_provider_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='currency',
            field=models.CharField(choices=[('US Dollars', 'USD'), ('Australia Dollar', 'AUD'), ('Great Britain Pound', 'GBP'), ('Bitcoin', 'BTC'), ('Nigerian Naira', 'NGN')], default='USD', max_length=254),
        ),
    ]
